# thibaud@jilion.com credentials
defaults: &defaults
  url: http://c76b85222fbec28c8508:7ab0d643924b2bcc23d2@api.pusherapp.com/apps/8211

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  url: <%= ENV['PUSHER_URL'] %>

production:
<% if ARGV.join.include? 'assets:precompile' %>
  <<: *defaults
<% else %>
  url: <%= ARGV.join.include?('assets:precompile') ? '' : ENV['PUSHER_URL'] %>
<% end %>